from enum import Enum

class ArtifactType(Enum):
    Spell_Scroll = "Spell Scroll"
    Centaur_s_Axe = "Centaur's Axe"
    Blackshard_of_the_Dead_Knight = "Blackshard of the Dead Knight"
    Greater_Gnoll_s_Flail = "Greater Gnoll's Flail"
    Ogre_s_Club_of_Havoc = "Ogre's Club of Havoc"
    Sword_of_Hellfire = "Sword of Hellfire"
    Titan_s_Gladius = "Titan's Gladius"
    Shield_of_the_Dwarven_Lords = "Shield of the Dwarven Lords"
    Shield_of_the_Yawning_Dead = "Shield of the Yawning Dead"
    Buckler_of_the_Gnoll_King = "Buckler of the Gnoll King"
    Targ_of_the_Rampaging_Ogre = "Targ of the Rampaging Ogre"
    Shield_of_the_Damned_ = "Shield of the Damned"
    Sentinel_s_Shield = "Sentinel's Shield"
    Helm_of_the_Alabaster_Unicorn = "Helm of the Alabaster Unicorn"
    Skull_Helmet = "Skull Helmet"
    Helm_of_Chaos = "Helm of Chaos"
    Crown_of_the_Supreme_Magi = "Crown of the Supreme Magi"
    Hellstorm_Helmet = "Hellstorm Helmet"
    Thunder_Helmet = "Thunder Helmet"
    Breastplate_of_Petrified_Wood = "Breastplate of Petrified Wood"
    Rib_Cage = "Rib Cage"
    Scales_of_the_Greater_Basilisk = "Scales of the Greater Basilisk"
    Tunic_of_the_Cyclops_King = "Tunic of the Cyclops King"
    Breastplate_of_Brimstone = "Breastplate of Brimstone"
    Titan_s_Cuirass = "Titan's Cuirass"
    Armor_of_Wonder = "Armor of Wonder"
    Sandals_of_the_Saint = "Sandals of the Saint"
    Celestial_Necklace_of_Bliss = "Celestial Necklace of Bliss"
    Lion_s_Shield_of_Courage = "Lion's Shield of Courage"
    Sword_of_Judgement = "Sword of Judgement"
    Helm_of_Heavenly_Enlightenment = "Helm of Heavenly Enlightenment"
    Quiet_Eye_of_the_Dragon = "Quiet Eye of the Dragon"
    Red_Dragon_Flame_Tongue = "Red Dragon Flame Tongue"
    Dragon_Scale_Shield = "Dragon Scale Shield"
    Dragon_Scale_Armor = "Dragon Scale Armor"
    Dragonbone_Greaves = "Dragonbone Greaves"
    Dragon_Wing_Tabard = "Dragon Wing Tabard"
    Necklace_of_Dragonteeth = "Necklace of Dragonteeth"
    Crown_of_Dragontooth = "Crown of Dragontooth"
    Still_Eye_of_the_Dragon = "Still Eye of the Dragon"
    Clover_of_Fortune = "Clover of Fortune"
    Cards_of_Prophecy = "Cards of Prophecy"
    Ladybird_of_Luck = "Ladybird of Luck"
    Badge_of_Courage = "Badge of Courage"
    Crest_of_Valor = "Crest of Valor"
    Glyph_of_Gallantry = "Glyph of Gallantry"
    Speculum = "Speculum"
    Spyglass = "Spyglass"
    Amulet_of_the_Undertaker = "Amulet of the Undertaker"
    Vampire_s_Cowl = "Vampire's Cowl"
    Dead_Man_s_Boots = "Dead Man's Boots"
    Garniture_of_Interference = "Garniture of Interference"
    Surcoat_of_Counterpoise = "Surcoat of Counterpoise"
    Boots_of_Polarity = "Boots of Polarity"
    Bow_of_Elven_Cherrywood = "Bow of Elven Cherrywood"
    Bowstring_of_the_Unicorn_s_Mane = "Bowstring of the Unicorn's Mane"
    Angel_Feather_Arrows = "Angel Feather Arrows"
    Bird_of_Perception = "Bird of Perception"
    Stoic_Watchman = "Stoic Watchman"
    Emblem_of_Cognizance = "Emblem of Cognizance"
    Statesman_s_Medal = "Statesman's Medal"
    Diplomat_s_Ring = "Diplomat's Ring"
    Ambassador_s_Sash = "Ambassador's Sash"
    Ring_of_the_Wayfarer = "Ring of the Wayfarer"
    Equestrian_s_Gloves = "Equestrian's Gloves"
    Necklace_of_Ocean_Guidance = "Necklace of Ocean Guidance"
    Angel_Wings = "Angel Wings"
    Charm_of_Mana = "Charm of Mana"
    Talisman_of_Mana = "Talisman of Mana"
    Mystic_Orb_of_Mana = "Mystic Orb of Mana"
    Collar_of_Conjuring = "Collar of Conjuring"
    Ring_of_Conjuring = "Ring of Conjuring"
    Cape_of_Conjuring = "Cape of Conjuring"
    Orb_of_the_Firmament = "Orb of the Firmament"
    Orb_of_Silt = "Orb of Silt"
    Orb_of_Tempestuous_Fire = "Orb of Tempestuous Fire"
    Orb_of_Driving_Rain = "Orb of Driving Rain"
    Recanter_s_Cloak = "Recanter's Cloak"
    Spirit_of_Oppression = "Spirit of Oppression"
    Hourglass_of_the_Evil_Hour = "Hourglass of the Evil Hour"
    Tome_of_Fire = "Tome of Fire"
    Tome_of_Air = "Tome of Air"
    Tome_of_Water = "Tome of Water"
    Tome_of_Earth = "Tome of Earth"
    Boots_of_Levitation = "Boots of Levitation"
    Golden_Bow = "Golden Bow"
    Sphere_of_Permanence = "Sphere of Permanence"
    Orb_of_Vulnerability = "Orb of Vulnerability"
    Ring_of_Vitality = "Ring of Vitality"
    Ring_of_Life = "Ring of Life"
    Vial_of_Lifeblood = "Vial of Lifeblood"
    Necklace_of_Swiftness = "Necklace of Swiftness"
    Boots_of_Speed = "Boots of Speed"
    Cape_of_Velocity = "Cape of Velocity"
    Pendant_of_Dispassion = "Pendant of Dispassion"
    Pendant_of_Second_Sight = "Pendant of Second Sight"
    Pendant_of_Holiness = "Pendant of Holiness"
    Pendant_of_Life = "Pendant of Life"
    Pendant_of_Death = "Pendant of Death"
    Pendant_of_Free_Will = "Pendant of Free Will"
    Pendant_of_Negativity = "Pendant of Negativity"
    Pendant_of_Total_Recall = "Pendant of Total Recall"
    Pendant_of_Courage = "Pendant of Courage"
    Everflowing_Crystal_Cloak = "Everflowing Crystal Cloak"
    Ring_of_Infinite_Gems = "Ring of Infinite Gems"
    Everpouring_Vial_of_Mercury = "Everpouring Vial of Mercury"
    Inexhaustible_Cart_of_Ore = "Inexhaustible Cart of Ore"
    Eversmoking_Ring_of_Sulfur = "Eversmoking Ring of Sulfur"
    Inexhaustible_Cart_of_Lumber = "Inexhaustible Cart of Lumber"
    Endless_Sack_of_Gold = "Endless Sack of Gold"
    Endless_Bag_of_Gold = "Endless Bag of Gold"
    Endless_Purse_of_Gold = "Endless Purse of Gold"
    Legs_of_Legion = "Legs of Legion"
    Loins_of_Legion = "Loins of Legion"
    Torso_of_Legion = "Torso of Legion"
    Arms_of_Legion = "Arms of Legion"
    Head_of_Legion = "Head of Legion"
    Sea_Captain_s_Hat = "Sea Captain's Hat"
    Spellbinder_s_Hat = "Spellbinder's Hat"
    Shackles_of_War = "Shackles of War"
    Orb_of_Inhibition = "Orb of Inhibition"
    Vial_of_Dragon_Blood = "Vial of Dragon Blood"
    Armageddon_s_Blade = "Armageddon's Blade"
    Angelic_Alliance = "Angelic Alliance"
    Cloak_of_the_Undead_King = "Cloak of the Undead King"
    Elixir_of_Life = "Elixir of Life"
    Armor_of_the_Damned = "Armor of the Damned"
    Statue_of_Legion = "Statue of Legion"
    Power_of_the_Dragon_Father = "Power of the Dragon Father"
    Titan_s_Thunder = "Titan's Thunder"
    Admiral_s_Hat = "Admiral's Hat"
    Bow_of_the_Sharpshooter = "Bow of the Sharpshooter"
    Wizard_s_Well = "Wizard's Well"
    Ring_of_the_Magi = "Ring of the Magi"
    Cornucopia = "Cornucopia"

class ArtifactNum(Enum):
    Spell_Scroll = 1
    Centaur_s_Axe = 7
    Blackshard_of_the_Dead_Knight = 8
    Greater_Gnoll_s_Flail = 9
    Ogre_s_Club_of_Havoc = 10
    Sword_of_Hellfire = 11
    Titan_s_Gladius = 12
    Shield_of_the_Dwarven_Lords = 13
    Shield_of_the_Yawning_Dead = 14
    Buckler_of_the_Gnoll_King = 15
    Targ_of_the_Rampaging_Ogre = 16
    Shield_of_the_Damned_ = 17
    Sentinel_s_Shield = 18
    Helm_of_the_Alabaster_Unicorn = 19
    Skull_Helmet = 20
    Helm_of_Chaos = 21
    Crown_of_the_Supreme_Magi = 22
    Hellstorm_Helmet = 23
    Thunder_Helmet = 24
    Breastplate_of_Petrified_Wood = 25
    Rib_Cage = 26
    Scales_of_the_Greater_Basilisk = 27
    Tunic_of_the_Cyclops_King = 28
    Breastplate_of_Brimstone = 29
    Titan_s_Cuirass = 30
    Armor_of_Wonder = 31
    Sandals_of_the_Saint = 32
    Celestial_Necklace_of_Bliss = 33
    Lion_s_Shield_of_Courage = 34
    Sword_of_Judgement = 35
    Helm_of_Heavenly_Enlightenment = 36
    Quiet_Eye_of_the_Dragon = 37
    Red_Dragon_Flame_Tongue = 38
    Dragon_Scale_Shield = 39
    Dragon_Scale_Armor = 40
    Dragonbone_Greaves = 41
    Dragon_Wing_Tabard = 42
    Necklace_of_Dragonteeth = 43
    Crown_of_Dragontooth = 44
    Still_Eye_of_the_Dragon = 45
    Clover_of_Fortune = 46
    Cards_of_Prophecy = 47
    Ladybird_of_Luck = 48
    Badge_of_Courage = 49
    Crest_of_Valor = 50
    Glyph_of_Gallantry = 51
    Speculum = 52
    Spyglass = 53
    Amulet_of_the_Undertaker = 54
    Vampire_s_Cowl = 55
    Dead_Man_s_Boots = 56
    Garniture_of_Interference = 57
    Surcoat_of_Counterpoise = 58
    Boots_of_Polarity = 59
    Bow_of_Elven_Cherrywood = 60
    Bowstring_of_the_Unicorn_s_Mane = 61
    Angel_Feather_Arrows = 62
    Bird_of_Perception = 63
    Stoic_Watchman = 64
    Emblem_of_Cognizance = 65
    Statesman_s_Medal = 66
    Diplomat_s_Ring = 67
    Ambassador_s_Sash = 68
    Ring_of_the_Wayfarer = 69
    Equestrian_s_Gloves = 70
    Necklace_of_Ocean_Guidance = 71
    Angel_Wings = 72
    Charm_of_Mana = 73
    Talisman_of_Mana = 74
    Mystic_Orb_of_Mana = 75
    Collar_of_Conjuring = 76
    Ring_of_Conjuring = 77
    Cape_of_Conjuring = 78
    Orb_of_the_Firmament = 79
    Orb_of_Silt = 80
    Orb_of_Tempestuous_Fire = 81
    Orb_of_Driving_Rain = 82
    Recanter_s_Cloak = 83
    Spirit_of_Oppression = 84
    Hourglass_of_the_Evil_Hour = 85
    Tome_of_Fire = 86
    Tome_of_Air = 87
    Tome_of_Water = 88
    Tome_of_Earth = 89
    Boots_of_Levitation = 90
    Golden_Bow = 91
    Sphere_of_Permanence = 92
    Orb_of_Vulnerability = 93
    Ring_of_Vitality = 94
    Ring_of_Life = 95
    Vial_of_Lifeblood = 96
    Necklace_of_Swiftness = 97
    Boots_of_Speed = 98
    Cape_of_Velocity = 99
    Pendant_of_Dispassion = 100
    Pendant_of_Second_Sight = 101
    Pendant_of_Holiness = 102
    Pendant_of_Life = 103
    Pendant_of_Death = 104
    Pendant_of_Free_Will = 105
    Pendant_of_Negativity = 106
    Pendant_of_Total_Recall = 107
    Pendant_of_Courage = 108
    Everflowing_Crystal_Cloak = 109
    Ring_of_Infinite_Gems = 110
    Everpouring_Vial_of_Mercury = 111
    Inexhaustible_Cart_of_Ore = 112
    Eversmoking_Ring_of_Sulfur = 113
    Inexhaustible_Cart_of_Lumber = 114
    Endless_Sack_of_Gold = 115
    Endless_Bag_of_Gold = 116
    Endless_Purse_of_Gold = 117
    Legs_of_Legion = 118
    Loins_of_Legion = 119
    Torso_of_Legion = 120
    Arms_of_Legion = 121
    Head_of_Legion = 122
    Sea_Captain_s_Hat = 123
    Spellbinder_s_Hat = 124
    Shackles_of_War = 125
    Orb_of_Inhibition = 126
    Vial_of_Dragon_Blood = 127
    Armageddon_s_Blade = 129
    Angelic_Alliance = 130
    Cloak_of_the_Undead_King = 131
    Elixir_of_Life = 132
    Armor_of_the_Damned = 133
    Statue_of_Legion = 134
    Power_of_the_Dragon_Father = 135
    Titan_s_Thunder = 136
    Admiral_s_Hat = 137
    Bow_of_the_Sharpshooter = 138
    Wizard_s_Well = 139
    Ring_of_the_Magi = 140
    Cornucopia = 141

def converterNumToType(num: ArtifactNum):
    for values in ArtifactType:
        if ArtifactNum(num).name == values.name:
            return values.value

def converterTypeToNum(type: ArtifactType):
    for values in ArtifactNum:
        if ArtifactType(type).name == values.name:
            return values.value