from enum import Enum

class CreatureType(Enum):
    Pikeman = "Pikeman"
    Halberdier = "Halberdier"
    Archer = "Archer"
    Marksman = "Marksman"
    Griffin = "Griffin"
    Royal_Griffin = "Royal Griffin"
    Swordsman = "Swordsman"
    Crusader = "Crusader"
    Monk = "Monk"
    Zealot = "Zealot"
    Cavalier = "Cavalier"
    Champion = "Champion"
    Angel = "Angel"
    Archangel = "Archangel"
    Centaur = "Centaur"
    Centaur_Captain = "Centaur Captain"
    Dwarf = "Dwarf"
    Battle_Dwarf = "Battle Dwarf"
    Wood_Elf = "Wood Elf"
    Grand_Elf = "Grand Elf"
    Pegasus = "Pegasus"
    Silver_Pegasus = "Silver Pegasus"
    Dendroid_Guard = "Dendroid Guard"
    Dendroid_Soldier = "Dendroid Soldier"
    Unicorn = "Unicorn"
    War_Unicorn = "War Unicorn"
    Green_Dragon = "Green Dragon"
    Gold_Dragon = "Gold Dragon"
    Gremlin = "Gremlin"
    Master_Gremlin = "Master Gremlin"
    Stone_Gargoyle = "Stone Gargoyle"
    Obsidian_Gargoyle = "Obsidian Gargoyle"
    Stone_Golem = "Stone Golem"
    Iron_Golem = "Iron Golem"
    Mage = "Mage"
    Arch_Mage = "Arch Mage"
    Genie = "Genie"
    Master_Genie = "Master Genie"
    Naga = "Naga"
    Naga_Queen = "Naga Queen"
    Giant = "Giant"
    Titan = "Titan"
    Imp = "Imp"
    Familiar = "Familiar"
    Gog = "Gog"
    Magog = "Magog"
    Hell_Hound = "Hell Hound"
    Cerberus = "Cerberus"
    Demon = "Demon"
    Horned_Demon = "Horned Demon"
    Pit_Fiend = "Pit Fiend"
    Pit_Lord = "Pit Lord"
    Efreeti = "Efreeti"
    Efreet_Sultan = "Efreet Sultan"
    Devil = "Devil"
    Arch_Devil = "Arch Devil"
    Skeleton = "Skeleton"
    Skeleton_Warrior = "Skeleton Warrior"
    Walking_Dead = "Walking Dead"
    Zombie = "Zombie"
    Wight = "Wight"
    Wraith = "Wraith"
    Vampire = "Vampire"
    Vampire_Lord = "Vampire Lord"
    Lich = "Lich"
    Power_Lich = "Power Lich"
    Black_Knight = "Black Knight"
    Dread_Knight = "Dread Knight"
    Bone_Dragon = "Bone Dragon"
    Ghos_Dragon = "Ghost Dragon"
    Troglodyte = "Troglodyte"
    Infernal_Troglodyte = "Infernal Troglodyte"
    Harpy = "Harpy"
    Harpy_Hag = "Harpy Hag"
    Beholder = "Beholder"
    Evil_Eye = "Evil Eye"
    Medusa = "Medusa"
    Medusa_Queen = "Medusa Queen"
    Minotaur = "Minotaur"
    Minotaur_King = "Minotaur King"
    Manticore = "Manticore"
    Scorpicore = "Scorpicore"
    Red_Dragon = "Red Dragon"
    Black_Dragon = "Black Dragon"
    Goblin = "Goblin"
    Hobgoblin = "Hobgoblin"
    Wolf_Rider = "Wolf Rider"
    Wolf_Raider = "Wolf Raider"
    Orc = "Orc"
    Orc_Chieftain = "Orc Chieftain"
    Ogre = "Ogre"
    Ogre_Mage = "Ogre Mage"
    Roc = "Roc"
    Thunderbird = "Thunderbird"
    Cyclops = "Cyclops"
    Cyclops_King = "Cyclops King"
    Behemoth = "Behemoth"
    Ancient_Behemoth = "Ancient Behemoth"
    Gnoll = "Gnoll"
    Gnoll_Marauder = "Gnoll Marauder"
    Lizardman = "Lizardman"
    Lizard_Warrior = "Lizard Warrior"
    Serpent_Fly = "Serpent Fly"
    Dragon_Fly = "Dragon Fly"
    Basilisk = "Basilisk"
    Greater_Basilisk = "Greater Basilisk"
    Gorgon = "Gorgon"
    Mighty_Gorgon = "Mighty Gorgon"
    Wyvern = "Wyvern"
    Wyvern_Monarch = "Wyvern Monarch"
    Hydra = "Hydra"
    Chaos_Hydra = "Chaos Hydra"
    Pixie = "Pixie"
    Sprite = "Sprite"
    Air_Elemental = "Air Elemental"
    Storm_Elemental = "Storm Elemental"
    Water_Elemental = "Water Elemental"
    Ice_Elemental = "Ice Elemental"
    Fire_Elemental = "Fire Elemental"
    Energy_Elemental = "Energy Elemental"
    Earth_Elemental = "Earth Elemental"
    Magma_Elemental = "Magma Elemental"
    Psychic_Elemental = "Psychic Elemental"
    Magic_Elemental = "Magic Elemental"
    Firebird = "Firebird"
    Phoenix = "Phoenix"


class CreatureNum(Enum):
    Pikeman = 0
    Halberdier = 1
    Archer = 2
    Marksman = 3
    Griffin = 4
    Royal_Griffin = 5
    Swordsman = 6
    Crusader = 7
    Monk = 8
    Zealot = 9
    Cavalier = 10
    Champion = 11
    Angel = 12
    Archangel = 13
    Centaur = 14
    Centaur_Captain = 15
    Dwarf = 16
    Battle_Dwarf = 17
    Wood_Elf = 18
    Grand_Elf = 19
    Pegasus = 20
    Silver_Pegasus = 21
    Dendroid_Guard = 22
    Dendroid_Soldier = 23
    Unicorn = 24
    War_Unicorn = 25
    Green_Dragon = 26
    Gold_Dragon = 27
    Gremlin = 28
    Master_Gremlin = 29
    Stone_Gargoyle = 30
    Obsidian_Gargoyle = 31
    Stone_Golem = 32
    Iron_Golem = 33
    Mage = 34
    Arch_Mage = 35
    Genie = 36
    Master_Genie = 37
    Naga = 38
    Naga_Queen = 39
    Giant = 40
    Titan = 41
    Imp = 42
    Familiar = 43
    Gog = 44
    Magog = 45
    Hell_Hound = 46
    Cerberus = 47
    Demon = 48
    Horned_Demon = 49
    Pit_Fiend = 50
    Pit_Lord = 51
    Efreeti = 52
    Efreet_Sultan = 53
    Devil = 54
    Arch_Devil = 55
    Skeleton = 56
    Skeleton_Warrior = 57
    Walking_Dead = 58
    Zombie = 59
    Wight = 60
    Wraith = 61
    Vampire = 62
    Vampire_Lord = 63
    Lich = 64
    Power_Lich = 65
    Black_Knight = 66
    Dread_Knight = 67
    Bone_Dragon = 68
    Ghost_Dragon = 69
    Troglodyte = 70
    Infernal_Troglodyte = 71
    Harpy = 72
    Harpy_Hag = 73
    Beholder = 74
    Evil_Eye = 75
    Medusa = 76
    Medusa_Queen = 77
    Minotaur = 78
    Minotaur_King = 79
    Manticore = 80
    Scorpicore = 81
    Red_Dragon = 82
    Black_Dragon = 83
    Goblin = 84
    Hobgoblin = 85
    Wolf_Rider = 86
    Wolf_Raider = 87
    Orc = 88
    Orc_Chieftain = 89
    Ogre = 90
    Ogre_Mage = 91
    Roc = 92
    Thunderbird = 93
    Cyclops = 94
    Cyclops_King = 95
    Behemoth = 96
    Ancient_Behemoth = 97
    Gnoll = 98
    Gnoll_Marauder = 99
    Lizardman = 100
    Lizard_Warrior = 101
    Serpent_Fly = 102
    Dragon_Fly = 103
    Basilisk = 104
    Greater_Basilisk = 105
    Gorgon = 106
    Mighty_Gorgon = 107
    Wyvern = 108
    Wyvern_Monarch = 109
    Hydra = 110
    Chaos_Hydra = 111
    Pixie = 112
    Sprite = 113
    Air_Elemental = 114
    Storm_Elemental = 115
    Water_Elemental = 116
    Ice_Elemental = 117
    Fire_Elemental = 118
    Energy_Elemental = 119
    Earth_Elemental = 120
    Magma_Elemental = 121
    Psychic_Elemental = 122
    Magic_Elemental = 123
    Firebird = 124
    Phoenix = 125


def converterNumToType(num: CreatureNum):
    for values in CreatureType:
        if CreatureNum(num).name == values.name:
            return values.value

def converterTypeToNum(type: CreatureType):
    for values in CreatureNum:
        if CreatureType(type).name == values.name:
            return values.value

