class DisabledSpells:
    def __init__(self):
        self.summon_boat= False
        self.scuttle_boat= False
        self.visions= False
        self.view_earth= False
        self.disguise= False
        self.view_air= False
        self.fly= False
        self.water_walk= False
        self.dimension_door= False
        self.town_portal= False
        self.quick_sand= False
        self.land_mine= False
        self.force_field= False
        self.fire_wall= False
        self.earthquake= False
        self.magic_arrow= False
        self.ice_bolt= False
        self.lightning_bolt= False
        self.implosion= False
        self.chain_lightning= False
        self.frost_ring= False
        self.fireball= False
        self.inferno= False
        self.meteor_shower= False
        self.death_ripple= False
        self.destroy_undead= False
        self.armageddon= False
        self.shield= False
        self.air_shield= False
        self.fire_shield= False
        self.protection_from_air= False
        self.protection_from_fire= False
        self.protection_from_water= False
        self.protection_from_earth= False
        self.anti_magic= False
        self.dispel= False
        self.magic_mirror= False
        self.cure= False
        self.resurrection= False
        self.animate_dead= False
        self.sacrifice= False
        self.bless= False
        self.curse= False
        self.bloodlust= False
        self.precision= False
        self.weakness= False
        self.stone_skin= False
        self.disrupting_ray= False
        self.prayer= False
        self.mirth= False
        self.sorrow= False
        self.fortune= False
        self.misfortune= False
        self.haste= False
        self.slow= False
        self.slayer= False
        self.frenzy= False
        self.titans_lightning_bolt= False
        self.counterstrike= False
        self.berserk= False
        self.hypnotize= False
        self.forgetfulness= False
        self.blind= False
        self.teleport= False
        self.remove_obstacle= False
        self.clone= False
        self.fire_elemental= False
        self.earth_elemental= False
        self.water_elemental= False
        self.air_elemental= False
        self.padding_70= False
        self.padding_71= False

    def __init__(self, summon_boat: bool, scuttle_boat: bool, visions: bool, view_earth: bool, 
                 disguise: bool, view_air: bool, fly: bool, water_walk: bool, dimension_door: bool,
                 town_portal: bool, quick_sand: bool, land_mine: bool, force_field: bool,
                 fire_wall: bool, earthquake: bool, magic_arrow: bool, ice_bolt: bool,
                 lightning_bolt: bool, implosion: bool, chain_lightning: bool, frost_ring: bool,
                 fireball: bool, inferno: bool, meteor_shower: bool, death_ripple: bool,
                 destroy_undead: bool, armageddon: bool, shield: bool, air_shield: bool,
                 fire_shield: bool, protection_from_air: bool, protection_from_fire: bool,
                 protection_from_water: bool, protection_from_earth: bool, anti_magic: bool,
                 dispel: bool, magic_mirror: bool, cure: bool, resurrection: bool,
                 animate_dead: bool, sacrifice: bool, bless: bool, curse: bool,
                 bloodlust: bool, precision: bool, weakness: bool, stone_skin: bool,
                 disrupting_ray: bool, prayer: bool, mirth: bool, sorrow: bool,
                 fortune: bool, misfortune: bool, haste: bool, slow: bool,
                 slayer: bool, frenzy: bool, titans_lightning_bolt:bool,
                 counterstrike :bool , berserk :bool , hypnotize :bool , forgetfulness :bool ,
                 blind :bool , teleport :bool , remove_obstacle :bool , clone :bool ,
                 fire_elemental :bool , earth_elemental :bool , water_elemental :bool ,
                 air_elemental :bool , padding_70 :bool , padding_71 :bool):
        self.summon_boat= summon_boat
        self.scuttle_boat= scuttle_boat
        self.visions= visions
        self.view_earth= view_earth
        self.disguise= disguise
        self.view_air= view_air
        self.fly= fly
        self.water_walk= water_walk
        self.dimension_door= dimension_door
        self.town_portal= town_portal
        self.quick_sand= quick_sand
        self.land_mine= land_mine
        self.force_field= force_field
        self.fire_wall= fire_wall
        self.earthquake= earthquake
        self.magic_arrow= magic_arrow
        self.ice_bolt= ice_bolt
        self.lightning_bolt= lightning_bolt
        self.implosion= implosion
        self.chain_lightning= chain_lightning
        self.frost_ring= frost_ring
        self.fireball= fireball
        self.inferno= inferno
        self.meteor_shower= meteor_shower
        self.death_ripple= death_ripple
        self.destroy_undead= destroy_undead
        self.armageddon= armageddon
        self.shield= shield
        self.air_shield= air_shield
        self.fire_shield= fire_shield
        self.protection_from_air= protection_from_air
        self.protection_from_fire= protection_from_fire
        self.protection_from_water= protection_from_water
        self.protection_from_earth= protection_from_earth
        self.anti_magic= anti_magic
        self.dispel= dispel
        self.magic_mirror= magic_mirror
        self.cure= cure
        self.resurrection= resurrection
        self.animate_dead= animate_dead
        self.sacrifice= sacrifice
        self.bless= bless
        self.curse= curse
        self.bloodlust= bloodlust
        self.precision= precision
        self.weakness= weakness
        self.stone_skin= stone_skin
        self.disrupting_ray= disrupting_ray
        self.prayer= prayer
        self.mirth= mirth
        self.sorrow= sorrow
        self.fortune= fortune
        self.misfortune= misfortune
        self.haste= haste
        self.slow= slow
        self.slayer= slayer
        self.frenzy= frenzy
        self.titans_lightning_bolt= titans_lightning_bolt
        self.counterstrike= counterstrike
        self.berserk= berserk
        self.hypnotize= hypnotize
        self.forgetfulness= forgetfulness
        self.blind= blind
        self.teleport= teleport
        self.remove_obstacle= remove_obstacle
        self.clone= clone
        self.fire_elemental= fire_elemental
        self.earth_elemental= earth_elemental
        self.water_elemental= water_elemental
        self.air_elemental= air_elemental
        self.padding_70= padding_70
        self.padding_71= padding_71

    def to_dict(self):
        return {
            "summon_boat": self.summon_boat,
            "scuttle_boat": self.scuttle_boat,
            "visions": self.visions,
            "view_earth": self.view_earth,
            "disguise": self.disguise,
            "view_air": self.view_air,
            "fly": self.fly,
            "water_walk": self.water_walk,
            "dimension_door": self.dimension_door,
            "town_portal": self.town_portal,
            "quick_sand": self.quick_sand,
            "land_mine": self.land_mine,
            "force_field": self.force_field,
            "fire_wall": self.fire_wall,
            "earthquake": self.earthquake,
            "magic_arrow": self.magic_arrow,
            "ice_bolt": self.ice_bolt,
            "lightning_bolt": self.lightning_bolt,
            "implosion": self.implosion,
            "chain_lightning": self.chain_lightning,
            "frost_ring": self.frost_ring,
            "fireball": self.fireball,
            "inferno": self.inferno,
            "meteor_shower": self.meteor_shower,
            "death_ripple": self.death_ripple,
            "destroy_undead": self.destroy_undead,
            "armageddon": self.armageddon,
            "shield": self.shield,
            "air_shield": self.air_shield,
            "fire_shield": self.fire_shield,
            "protection_from_air": self.protection_from_air,
            "protection_from_fire": self.protection_from_fire,
            "protection_from_water": self.protection_from_water,
            "protection_from_earth": self.protection_from_earth,
            "anti_magic": self.anti_magic,
            "dispel": self.dispel,
            "magic_mirror": self.magic_mirror,
            "cure": self.cure,
            "resurrection": self.resurrection,
            "animate_dead": self.animate_dead,
            "sacrifice": self.sacrifice,
            "bless": self.bless,
            "curse": self.curse,
            "bloodlust": self.bloodlust,
            "precision": self.precision,
            "weakness": self.weakness,
            "stone_skin": self.stone_skin,
            "disrupting_ray": self.disrupting_ray,
            "prayer": self.prayer,
            "mirth": self.mirth,
            "sorrow": self.sorrow,
            "fortune": self.fortune,
            "misfortune": self.misfortune,
            "haste": self.haste,
            "slow": self.slow,
            "slayer": self.slayer,
            "frenzy": self.frenzy,
            "titans_lightning_bolt": self.titans_lightning_bolt,
            "counterstrike": self.counterstrike,
            "berserk": self.berserk,
            "hypnotize": self.hypnotize,
            "forgetfulness": self.forgetfulness,
            "blind": self.blind,
            "teleport": self.teleport,
            "remove_obstacle": self.remove_obstacle,
            "clone": self.clone,
            "fire_elemental": self.fire_elemental,
            "earth_elemental": self.earth_elemental,
            "water_elemental": self.water_elemental,
            "air_elemental": self.air_elemental,
            "padding_70": self.padding_70,
            "padding_71": self.padding_71
        }